#include "ecritum.h"

int main() {
    ecritum_runtime_t runtime = 0;
    ecritum_context_t context = 0;
    ecritum_namespace_t namespace_handle = 0;
    ecritum_function_t function = 0;
    ecritum_value_t value = 0;
    ecritum_call_t call = 0;
    ecritum_job_t job = 0;
    ecritum_error_t error = 0;
    ecritum_bytes_t bytes = {0};
    ecritum_string_view_t view = {0};
    ecritum_object_entry_t object_entry = {view, value};
    ecritum_host_fn_t callback = nullptr;
    ecritum_user_data_destroy_fn_t destroy_user_data = nullptr;
    int value_kind = ECRITUM_VALUE_KIND_INT;
    int job_state = ECRITUM_JOB_SUCCEEDED;

    (void)runtime;
    (void)context;
    (void)namespace_handle;
    (void)function;
    (void)value;
    (void)call;
    (void)job;
    (void)error;
    (void)bytes;
    (void)view;
    (void)object_entry;
    (void)callback;
    (void)destroy_user_data;
    (void)value_kind;
    (void)job_state;
    (void)&ecritum_value_make_null;
    (void)&ecritum_value_make_bool;
    (void)&ecritum_value_make_int;
    (void)&ecritum_value_make_double;
    (void)&ecritum_value_make_string;
    (void)&ecritum_value_make_data;
    (void)&ecritum_value_make_array;
    (void)&ecritum_value_make_object;
    (void)&ecritum_value_destroy;
    (void)&ecritum_value_kind;
    (void)&ecritum_value_get_bool;
    (void)&ecritum_value_get_int;
    (void)&ecritum_value_get_double;
    (void)&ecritum_value_get_string;
    (void)&ecritum_value_get_data;
    (void)&ecritum_value_count;
    (void)&ecritum_value_array_get;
    (void)&ecritum_value_object_entry;
    (void)&ecritum_call_argument_count;
    (void)&ecritum_call_argument;
    (void)&ecritum_eval_start;
    (void)&ecritum_job_poll;
    (void)&ecritum_job_wait;
    (void)&ecritum_job_cancel;
    (void)&ecritum_job_result;
    (void)&ecritum_job_destroy;
    (void)&ecritum_error_destroy;
    (void)&ecritum_error_status;
    (void)&ecritum_error_category;
    (void)&ecritum_error_message;
    (void)&ecritum_error_operation;
    (void)&ecritum_error_language;
    (void)&ecritum_error_source_name;
    return ECRITUM_OK;
}
